services:
  db:
    image: mysql:8.0
    container_name: mysql_app_db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: tesT*_p@ss12
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: tesT*_p@ss12
    networks:
      - services_network

  useridentity:
    image: useridentity
    build:
      context: .
      dockerfile: UserIdentity/Dockerfile
    container_name: useridentity
    ports:
      - 5000:80
      - 5001:8080
    environment:
      MysqlSettings__Host: db
      MysqlSettings__Port: 3306
      DB_MysqlSettings__Database: test_db
      MysqlSettings__UserName: test_user
      MysqlSettings__Password: tesT*_p@ss12
      JwtIssuerOptions__Issuer: appv1
      JwtIssuerOptions__ValidForSeconds: 10
      JwtIssuerOptions__Audience: https://test.app.com
      KeySetOptions__KeyId: V1APP_KEY_IDV1
      KeySetOptions__PrivateKeyPath: ${APP_PRIVATE_KEY_PATH}
      KeySetOptions__PublicKeyPath: ${APP_PUBLIC_KEY_PATH}
      KeySetOptions__PrivateKeyPassPhrase: ${APP_PRIVATE_KEY_PASS_PHRASE}
      RoleSettings__DefaultRole: app-user,
      RoleSettings__AdminRoles: "administrator, super-administrator"
      ApiKeySettings__ApiKey: ${API_KEY}
      CorsSettings__AllowedOrigins: "*"
      DefaultResetPasswordMessage: If we have an account matching your email address, you will receive an email with a link to reset your password.     
    volumes:
      - ./certs:/certs
    depends_on:
      - db
    networks:
      - services_network
    restart: on-failure

networks:
  services_network:
    name: app_services_network
    driver: bridge
    