version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql_app_db
    environment:
      MYSQL_ROOT_PASSWORD: tesT*_p@ss12
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: tesT*_p@ss12
    networks:
      - services_network

  useridentity:
    image: useridentity
    build:
      context: .
      dockerfile: UserIdentity/Dockerfile
    container_name: useridentity
    ports:
      - 5000:80

    environment:
      DB_SERVER: db
      DB_PORT: 3306
      DB_NAME: test_db
      DB_USER: test_user
      DB_PASSWORD: tesT*_p@ss12
      APP_ISSUER: appv1
      APP_VALID_FOR: 10
      APP_AUDIENCE: https://test.app.com
      APP_KEY_ID: V1APP_KEY_IDV1
      APP_SECRET_KEY: c8pgjBdXIJtjbaEAvzEt
      APP_DEFAULT_ROLE: Default
      APP_DEFAULT_RESET_PASSWORD_MESSAGE: If we have an account matching your email address, you will receive an email with a link to reset your password.
    depends_on:
      - db
    networks:
      - services_network
    restart: on-failure

networks:
  services_network:
    name: app_services_network
    driver: bridge